services:
  db:
    image: mysql:8.4
    container_name: club_deportivo_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_NAME:-club_deportivo}
      MYSQL_USER: ${DB_USER:-app_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-app_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Si la base de datos está vacía (es decir, la primera vez que levantas el proyecto), MySQL revisa la carpeta /docker-entrypoint-initdb.d/ y ejecuta los scripts de esa carpeta
      - ./database/init_db.sql:/sql/01-init_db.sql:ro                    # Read Only (Copia el script de init en el contenedor)
      - ./database/seed.sql:/sql/02-seed.sql:ro                          # Read Only (Copia el script de seed de la db en el contenedor)
      - ./database/initdb.sh:/docker-entrypoint-initdb.d/00-initdb.sh:ro # Read Only (Copia el script que ejecuta correctamente ambos scripts .sql)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3306", "-u", "root", "-p${DB_ROOT_PASSWORD:-root_password}"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 90s

volumes:
  mysql_data: